const processData = async () => {
    throw new Error('Something went wrong')
    return 12
};
